#!/bin/bash

date=`date +%Y-%m-%d`
timestr=$(($(date +'%s * 1000 + %-N / 1000000')))

if [ -z "$name" ]; then
	name=$timestr
else
	name="${name}_${timestr}"
fi

mkdir -p "experiments"
dir=experiments/$name
init_dir=$(pwd)

git checkout --quiet -B working
git add -A
git commit --quiet --allow-empty -m "Experiment $name"
git push --quiet origin working


echo "Cloining project into in $dir"
mkdir -p "$dir"
cd "$dir"
git clone --quiet -b working --recurse-submodules --depth 1 git@github.com:insperatum/text-patterns.git . >/dev/null #quiet doesn't seem to work with submodules?

ln -s $init_dir/envs #anaconda-project

echo "Launching"
if [ "$1" == "-i" ]; then
	anaconda-project run train ${@:2}
else
	om-repeat sbatch -J "$name" -o slurm-logs/%j.out --gres=gpu:titan-x:1 --qos=tenenbaum --mem=40G -c10 --time=60 anaconda-project run train $@
fi
