#!/bin/bash

date=`date +%Y-%m-%d`
timestr=$(($(date +'%s * 1000 + %-N / 1000000')))

if [ -z "$name" ]; then
	name=$timestr
else
	name="${name}_${timestr}"
fi

dir=experiments/$name
init_dir=$(pwd)

git checkout --quiet -B working || exit
git pull --no-edit --quiet origin working || exit
git add -A || exit
git commit --quiet --allow-empty -m "Experiment $name" || exit
git push --quiet origin working || exit

echo "Cloining project into in $dir"
mkdir -p "$dir"
cd "$dir"
git clone --quiet -b working --recurse-submodules --depth 1 git@github.com:insperatum/text-patterns.git . || exit
git remote set-url --push origin no_push

ln -s $init_dir/envs #anaconda-project

echo "Launching"
if [ "$1" == "-i" ]; then
	anaconda-project run train ${@:2}
else
	om-repeat sbatch -J "$name" -o slurm-logs/%j.out --gres=gpu:titan-x:1 --qos=tenenbaum --mem=60G -c20 --time=120 anaconda-project run train $@
fi
