#!/bin/bash

date=`date +%Y-%m-%d`
timestr=$(($(date +'%s * 1000 + %-N / 1000000')))

if [ -z "$name" ]; then
	name=$timestr
else
	name="${name}_${timestr}"
fi

dir=experiments/$name
init_dir=$(pwd)

echo date:$date
echo time:$timestr
echo name:$name

git checkout -B working
git add -A
git commit --allow-empty -m "Experiment $name"
git push origin working

echo "Launching in $dir"
mkdir -p "$dir"
cd "$dir"
git clone --recurse-submodules --depth 1 https://github.com/insperatum/text-patterns.git .
git checkout working

ln -s $init_dir/envs #anaconda-project

if [ "$1" = '-i' ]; then
	python train.py ${@:2}
else
	om-repeat sbatch -J "$name" -o slurm-logs/%j.out --gres=gpu:titan-x:1 --qos=tenenbaum --mem=40G -c10 --time=60 anaconda-project run train $@
fi
