#!/bin/bash
date=`date +%Y-%m-%d`
mkdir -p "slurm-logs/$date"
if [ -z "$name" ]; then
	om-repeat sbatch -o slurm-logs/$date/%x-%j.out --gres=gpu:titan-x:1 --qos=tenenbaum --mem=40G -c10 --time=60 anaconda-project run train $@
else
	om-repeat sbatch -J "$name" -o slurm-logs/$date/%x-%j.out --gres=gpu:titan-x:1 --qos=tenenbaum --mem=40G -c10 --time=60 anaconda-project run train $@
fi
